export const INTELLIGENCE_SHARING_RPT_SERVICE_URL=process.env.REACT_APP_INTELLIGENCE_SHARING_REPORT_SERVICE_URL;
export const SYSTEM_CONFIG_SERVICE_URL=process.env.REACT_APP_SYSTEM_CONFIG_SERVICE_URL;
export const USER_CONFIG_SERVICE_URL=process.env.REACT_APP_USER_CONFIG_SERVICE_URL;
export const CATSLAS_BACKEND_SERVICE_URL=process.env.REACT_APP_CATSLAS_BACKEND;
export const ENV_NAME=process.env.REACT_APP_ENV_NAME;
export const SYSTEM_VERSION=process.env.REACT_APP_SYSTEM_VERSION;
export const IS_SHOW_LOGIN_URL=process.env.REACT_APP_IS_SHOW_LOGIN;

export var FRAUD_CATEGORY_OTHERS : string = "FRAUD_CATEGORY_5";
export var FRAUD_TYPES_OTHERS : string[] = ["FRAUD_TYPE_3", "FRAUD_TYPE_6" , "FRAUD_TYPE_13" , "FRAUD_TYPE_16"];
export var SUSPICION_REASION_OTHERS: string = "REASON_8";
export var SOURCE_OTHERS: string = "SOURCE_8";

export const GENERIC_ERROR_MESSAGE : string = "Something went wrong. Please try again later.";

//page settings
export const DEFAULT_ROWS_PER_PAGE : number = 25;
export const DEFAULT_ROWS_PER_PAGE_OPTIONS : number[] = [10, 25, 50, 100];

// config keys
export const SESSION_EXTEND_REMINDER_TIMEOUT_SECONDS : string = 'SESSION_EXTEND_REMINDER_TIMEOUT_SECONDS'//;
export const SESSION_IDLE_LOGOUT_TIMEOUT_SECONDS : string = 'SESSION_IDLE_LOGOUT_TIMEOUT_SECONDS'//;
export const CONCURRENT_LOGIN_CHECK_INTERVAL_SECONDS: string = 'CONCURRENT_LOGIN_CHECK_INTERVAL_SECONDS'


export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT:string = "INTR-PL-001"
export const INT_PRIVILEGE_IMPORT_CORPORATE_MANAGER_USER:string = "INTR-PL-002"
export const INT_PRIVILEGE_MANAGE_CORPORATE_MANAGER_USER:string = "INTR-PL-003"
export const INT_PRIVILEGE_MANAGE_HKPF_USER:string = "INTR-PL-004"
export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT_FRAUD_CATEGORY_MAINTENANCE:string = "INTR-PL-005"
export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT_FRAUD_TYPE_MAINTENANCE:string = "INTR-PL-006"
export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT_SOURCE_MAINTENANCE:string = "INTR-PL-007"
export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT_REASON_FOR_SUSPICION_MAINTENANCE:string = "INTR-PL-008"
export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT_COUNTERPARTY_BANK_MAINTENANCE:string = "INTR-PL-009"
export const INT_PRIVILEGE_BANK_MAINTENANCE:string = "INTR-PL-010"
export const INT_PRIVILEGE_USER_GROUP_MAINTENANCE:string = "INTR-PL-011"
export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT_PLACE_OF_INCORPORATION_MAINTENANCE:string = "INTR-PL-012"

export const INT_PRIVILEGE_MAINTENANCE_ALERT_MAINTENANCE:string = "INTR-PL-014"
export const INT_PRIVILEGE_INTELLIGENCE_SHARING_REPORT_CONFIGURATION_TABLE_MAINTENANCE:string = "INTR-PL-013"
export const INT_PRIVILEGE_INTERNAL_HKPF_USER_MANAGEMENT = "INTR-PL-015"
export const INT_PRIVILEGE_AUDIT_LOG = "INTR-PL-016"


// user documemnt class
export const CATSLAS_PRIVILEGE_ENQUIRE_ACCESS_RIGHT_FOR_DOCUMENT_CLASS = "FN-RAR-01"
export const CATSLAS_PRIVILEGE_REQUEST_ACCESS_FOR_DOCUMENT_CLASS = "FN-RAR-02"
export const CATSLAS_PRIVILEGE_VERIFY_ACCESS_REQUEST_FOR_DOCUMENT_CLASS = "FN-RAR-03"
export const CATSLAS_PRIVILEGE_APPROVE_ACCESS_REQUEST_FOR_DOCUMENT_CLASS = "FN-RAR-04"
export const CATSLAS_PRIVILEGE_RETRIEVE_AND_DOWNLOAD_ARCHIVAL_RECORDS = "FN-RAR-06"

// Admin Function
export const CATSLAS_PRIVILEGE_SEARCH_USER_PROFILE = "FN-ADM-01"
export const CATSLAS_PRIVILEGE_MAINTAIN_USER_PROFILE = "FN-ADM-02"
export const CATSLAS_PRIVILEGE_MAINTAIN_DOCUMENT_CLASS = "FN-ADM-03"
export const CATSLAS_PRIVILEGE_MAINTAIN_SYSTEM_PARAMETERS = "FN-ADM-04"
export const CATSLAS_PRIVILEGE_IMPORT_TASKS_MAINTAIN = "FN-ADM-05"
export const CATSLAS_PRIVILEGE_IMPORT_TASKS_ENQUIRY = "FN-ADM-06"
export const CATSLAS_PRIVILEGE_MAINTAIN_TEAM_EMAIL_TEMPLATE = "FN-ADM-07"
export const CATSLAS_PRIVILEGE_SEND_EMAIL_FOR_ACCOUNT_ACCESS_REVIEW = "FN-ADM-08"

// Report Function
export const CATSLAS_PRIVILEGE_GENERATE_RGR_001 = "FN-RPT-01"
export const CATSLAS_PRIVILEGE_GENERATE_RGR_002 = "FN-RPT-02"
export const CATSLAS_PRIVILEGE_GENERATE_RGR_003 = "FN-RPT-03"
export const CATSLAS_PRIVILEGE_GENERATE_RGR_004 = "FN-RPT-04"
export const CATSLAS_PRIVILEGE_GENERATE_RGR_005 = "FN-RPT-05"
export const CATSLAS_PRIVILEGE_GENERATE_RGR_006 = "FN-RPT-06"
export const CATSLAS_PRIVILEGE_GENERATE_RGP_007 = "FN-RPT-07"
export const CATSLAS_PRIVILEGE_GENERATE_RGP_008 = "FN-RPT-08"
export const CATSLAS_PRIVILEGE_GENERATE_RGP_009 = "FN-RPT-09"
export const CATSLAS_PRIVILEGE_GENERATE_RGP_010 = "FN-RPT-10"
export const CATSLAS_PRIVILEGE_GENERATE_RGP_011 = "FN-RPT-11"


// Others
export const CATSLAS_PRIVILEGE_ENQUIRE_DISPOSAL_DATE_OF_ARCHIVAL_RECORDS = "FN-DAR-01"
export const CATSLAS_PRIVILEGE_EXTEND_DISPOSAL_DATE_OF_ARCHIVAL_RECORDS = "FN-DAR-02"

export const CATSLAS_PRIVILEGE_CHANGE_LANGUAGE = "FN-GEN-01"
export const CATSLAS_PRIVILEGE_ONLINE_HELP = "FN-GEN-02"

export const CATSLAS_PRIVILEGE_ENQUIRE_ACTIVITIES_LOG = "FN-AUD-03"
// test privilege
export const CATSLAS_PRIVILEGE_TEST = "FN-ADM-100"
